diagnostics:                      True
blockplot:                        False

signalfraction:                   0.3
ccr_of_bkg_fraction:              0.8
diffuse_of_astro_fraction:        0.3
Nevents:                          1000
nbins_mass:                       61
dmdensity_profile:                'einasto'
mass:                             1.0
mass_upper_bd_for_inference:      2.
mass_lower_bd_for_inference:      -1.
numcores:                         8

nbins_signalfraction:             31
sigfrac_upper_bd:                 1.
sigfrac_lower_bd:                 0.
sigfrac_spacing:                  'linear'

nbins_ccrfraction:                31
ccrfrac_upper_bd:                 1.
ccrfrac_lower_bd:                 0.
ccrfrac_spacing:                  'linear'

nbins_diffusefraction:            31
diffusefrac_upper_bd:             1.
diffusefrac_lower_bd:             0.
diffusefrac_spacing:              'linear'


true_energy_min:                  0.1
true_energy_max:                  100
true_energy_bins_per_decade:      50
true_spatial_res:                 0.2
true_longitude_min:               -3.5
true_longitude_max:               3.5
true_latitude_min:                -3
true_latitude_max:                3

recon_energy_min:                 0.1
recon_energy_max:                 100
recon_energy_bins_per_decade:     20
recon_spatial_res:                0.4
recon_longitude_min:              -3.5
recon_longitude_max:              3.5
recon_latitude_min:               -3
recon_latitude_max:               3


mixture_fraction_sampling:        'scan' # Either stochastic or scan


# Parameters for stochastic sampling if chosen
nestedsampler_kwarg_dict: {'nlive': 900}